services:
  restapi:
    image: ${DOCKER_REGISTRY-}restapi
    build:
      context: .
      dockerfile: RestApi/Dockerfile
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317/
    ports:
      - "61555:8081"
      - "61554:8080" 
    networks:
      - backend

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - backend

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"

networks:
    backend:
